baseURL = "https://www.logosfoundation.org/logoscollectie"
languageCode = "en-us"
title = "Catalogus van de logoscollectie"
googleAnalytics = "UA-143256397-1"
theme = "jeff"
[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    date = "dates"
	categorie = "categories"
    alfabet = "alfabetisch"
	
author = "Logos Foundation"
copyright = "Copyright © 2019-2020 Logos Foundation"
canonifyurls = true
paginate = 3
