baseURL = "https://www.logosfoundation.org/logoscollectie"
languageCode = "en-us"
title = "Catalogus van de logoscollectie"
googleAnalytics = "UA-143256397-1"
name = "Logoscollectie"
description = "Catalogus van de muziekinstrumenten uit de logoscollectie"
theme = "jeff"
license = "MIT"
licenselink = "https://github.com/Tazeg/hugo-blog-jeffprod/blob/master/LICENSE"

[permalinks]
    catalogus = "catalogus/:year/:filename"

[taxonomies]
    tag = "tags"
    date = "dates"
	categorie = "categories"
    alfabet = "alfabetisch"
